[package]
name = "kvdb_web_demo"
version = "0.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
repository = "https://github.com/paritytech/parity-common"
description = "Playground for kvdb in the browser"
license = "GPL-3.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
kvdb-web = { path = ".." }
wasm-bindgen = "0.2"
