[package]
name = "kvdb-web"
version = "0.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
repository = "https://github.com/paritytech/parity-common"
description = "A key-value database for use in browsers"
license = "GPL-3.0"
edition = "2018"

[dependencies]
wasm-bindgen = { version = "0.2", features = ['serde-serialize'] }
js-sys = "0.3.25"
kvdb = { version = "0.1", path = "../kvdb" }
serde_json = "1.0.40"
serde = { version = "1.0", features = ['derive'] }
base64 = "0.10.1"
hex = "0.3.2"

[dependencies.web-sys]
version = "0.3"
features = [
	'console',
	'Window',
	'Storage',
]
